import { Prompt, getPrompt } from '@/lib/data'
import Link from 'next/link'
import { useRouter } from 'next/router'
import Top from '../src/Top'
import styles from './[id].module.css'
import ReactMarkdown from 'react-markdown'
import Avatar from '../src/Avatar'
import UserAuth from '../src/UserAuth'
import GenerateButton from '../src/GenerateButton'

export default function Page({ id, prompt }: { id: String; prompt: Prompt }) {
  const router = useRouter()
  if (router.isFallback) {
    return <p>Loading...</p>
  }
  const { prompt: promptText, body, user, parent, children, timestamp } = prompt
  return (
    <div>
      {parent && (
        <p>
          <Link href={parent}>[&#8593; parent]</Link>
        </p>
      )}
      <Top text={promptText} />
      {body && <ReactMarkdown>{body}</ReactMarkdown>}
      {!body && (
        <p className={styles.notGeneratedYet}>
          This page&apos;s content has not been generated, yet.
        </p>
      )}
      {!body && <GenerateButton id={id} />}
      {user && (
        <p>
          generated by <Avatar user={user} />
          {timestamp && <> at {new Date(timestamp).toUTCString()}</>}
        </p>
      )}
      {children && (
        <ol className={styles.children}>
          {prompt.children?.map((child) => (
            <li key={child.id}>
              <Link href={child.id}>{child.prompt}</Link>
            </li>
          ))}
        </ol>
      )}
      {!body && <UserAuth />}
    </div>
  )
}

export const getStaticPaths = async () => {
  return {
    paths: [],
    fallback: true,
  }
}

export const getStaticProps = async ({
  params: { id },
}: {
  params: { id: string }
}) => {
  var prompt = await getPrompt(id)
  if (!prompt) {
    return {
      notFound: true,
    }
  }
  return {
    props: {
      id,
      prompt,
    },
  }
}
