import {
  BODY_SYSTEM_PROMPT,
  NEW_USER_CREDITS,
  SUGGESTION_SYSTEM_PROMPT,
} from '@/lib/globals'
import Link from 'next/link'
import Top from '../src/Top'
import styles from './faq.module.css'

export default function Index() {
  return (
    <>
      <Top text="MenuGPT.net FAQ" />
      <p className={styles.question}>What is it?</p>
      <p>
        MenuGpt.net a public webpage that provides a conversation with an AI.
        Unlike other chatbots, there is no freeform text entry. Instead, input
        choices are generated by the AI, and selected by the user. It&apos;s
        like a choose-your-own-adventure, for AI-chat. Each input and AI
        response gets a permanent and public web page. The pages are linked
        together by parent-child relationships. The result is a tree-shaped
        graph of pages.
      </p>
      <p className={styles.question}>Why does this exist?</p>
      <p>
        This is an exploration of unique ideas:
        <ol>
          <li>Using AI to generate static page content</li>
          <li>
            Lowering AI cost by making the conversation public, shared, and
            permanent
          </li>
          <li>Organizing AI chat in a tree, instead of using a transcript</li>
        </ol>
      </p>
      <p className={styles.question}>How does it work?</p>
      <p>
        Each page of the conversation is generated on-demand by users.{' '}
        <Link href="https://platform.openai.com/docs/api-reference/completions">
          OpenAI Chat Completion API
        </Link>{' '}
        is used to generate page content. Every page has a unique and permanent
        URL.
      </p>
      <p className={styles.question}>Is sign-in required?</p>
      <p>
        Pages are freely visible to anybody on the net. However, sign-in is
        required to generate additional pages, and to star pages.
      </p>
      <p className={styles.question}>What are starred pages?</p>
      <p>
        Signed-in users can star any pages they like. Stars are used to
        determine the top pages listed on the home page.
      </p>
      <p className={styles.question}>What are credits?</p>
      <p>
        The cost to generate a page is 1 credit. New accounts are granted{' '}
        {NEW_USER_CREDITS} credits. To request additional credits, contact the
        author. This is needed to keep costs down and prevent abuse. Payment for
        credits, ads, or other monetization may be added in the future.
      </p>
      <p className={styles.question}>How to contact the author?</p>
      <p>
        You can find the author&apos;s email address at the{' '}
        <Link href="https://github.com/landon9720">GitHub profile page</Link>{' '}
        (requires sign-in).
      </p>
      <p className={styles.question}>Where is the source?</p>
      <p>
        The project is an open source hobby project{' '}
        <Link href="https://github.com/landon9720/menugpt.net">
          hosted on GitHub.
        </Link>
      </p>
      <p className={styles.question}>Where to report bugs or issues?</p>
      <p>
        Report bugs or other issues{' '}
        <Link href="https://github.com/landon9720/menugpt.net/issues">
          here
        </Link>
        .
      </p>
      <p className={styles.question}>What internal pre-prompting is used?</p>
      <p>To generate the page body the following system prompt is used:</p>
      <blockquote>{BODY_SYSTEM_PROMPT}</blockquote>
      <p>To generate menu of responses, the following system prompt is used:</p>
      <blockquote>{SUGGESTION_SYSTEM_PROMPT}</blockquote>
    </>
  )
}
